### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AlexZd** [MerrickSapsford/Pageboy#11]
DataSource and Delegate should be `weak`

File `PageboyViewController.swift`

Line 27 should be
```public protocol PageboyViewControllerDelegate: class {```

Line 126 should be 
```public weak var dataSource: PageboyViewControllerDataSource? {```

Line 133 should be 
```public weak var delegate: PageboyViewControllerDelegate?```

PS: Sorry, haven't chance to create PR

**Comment by MerrickSapsford** [comment]
Oops my bad! 

Rectified in the PR above, will get it in another release ASAP.

**Comment by MerrickSapsford** [comment]
This is now fixed and available in [0.4.6](https://github.com/MerrickSapsford/Pageboy/releases/tag/0.4.6).
